openapi: 3.0.0
info:
  title: Solvro backend recruitment task - API for reserving tables in a restaurant
  version: 1.0.0
paths:
  /new-reservation:
    post:
      summary: Creates a new reservation for a table.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Reservation"
      responses:
        "201":
          description: New reservation created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservationId:
                    type: string
  /get-free-tables:
    post:
      summary: "Returns a list of all available tables based on the given time and number of people."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                duration:
                  type: string
                numberOfSeats:
                  type: number
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOfTables"
  /get-reservations:
    post:
      summary: "Returns a list of all reservations for the given date"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOfReservations"
  /request-cancellation:
    post:
      summary: "Requests a cancellation of the reservation"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reservationId:
                  type: number
      responses:
        "200":
          description: "OK"
  /verify-cancellation:
    post:
      summary: "Confirms the cancellation by checking the verification code"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                verificationCode:
                  type: number
      responses:
        "200":
          description: "OK"
components:
  schemas:
    Reservation:
      type: object
      properties:
        date:
          type: string
        duration:
          type: number
        seatNumber:
          type: number
        fullName:
          type: string
        phone:
          type: string
        email:
          type: string
        numberOfSeats:
          type: number
    ListOfReservations:
      type: object
      properties:
        bookings:
          type: array
          items:
            $ref: "#/components/schemas/Reservation"
    Table:
      type: object
      properties:
        number:
          type: number
        minNumberOfSeats:
          type: number
        maxNumberOfSeats:
          type: number
    ListOfTables:
      type: object
      properties:
        tables:
          type: array
          items:
            $ref: "#/components/schemas/Table"
